
import React from 'react';
import { AppTheme, MeraState } from '../types';
import { Network, X, Layers, Activity, Info } from 'lucide-react';

interface MeraSlateProps {
  state: MeraState;
  setState: React.Dispatch<React.SetStateAction<MeraState>>;
  theme: AppTheme;
  onClose: () => void;
}

const MeraSlate: React.FC<MeraSlateProps> = ({ state, setState, theme, onClose }) => {
  const bgClass = theme === 'primal' ? 'bg-slate-900/90 border-slate-700' : 'bg-white/95 border-slate-200 shadow-2xl';
  const textClass = theme === 'primal' ? 'text-slate-100' : 'text-slate-900';
  const accentClass = theme === 'primal' ? 'text-emerald-400' : 'text-emerald-600';

  return (
    <div className={`absolute left-20 top-8 w-80 p-6 backdrop-blur-xl border rounded-2xl z-40 animate-in slide-in-from-left duration-300 ${bgClass}`}>
      <div className="flex items-center justify-between mb-6 border-b border-white/10 pb-3">
        <div className="flex items-center gap-2">
          <Network className={accentClass} size={18} />
          <h2 className={`text-sm font-bold uppercase tracking-tight ${textClass}`}>MERA Decoder</h2>
        </div>
        <button onClick={onClose} className="text-slate-500 hover:text-white transition-colors">
          <X size={18} />
        </button>
      </div>

      <div className="space-y-6">
        <section>
          <div className="flex justify-between items-center mb-2">
            <span className="text-[10px] font-mono text-slate-500 uppercase">Renormalization Scale</span>
            <span className={`text-[10px] font-mono ${accentClass}`}>{Math.round(state.renormalizationScale * 100)}%</span>
          </div>
          <input 
            type="range" min="0" max="1" step="0.01" 
            value={state.renormalizationScale}
            onChange={e => setState(prev => ({ ...prev, renormalizationScale: parseFloat(e.target.value) }))}
            className="w-full h-1 bg-slate-800 rounded-full appearance-none cursor-pointer accent-emerald-500"
          />
        </section>

        <section>
          <div className="flex justify-between items-center mb-2">
            <span className="text-[10px] font-mono text-slate-500 uppercase">Bulk Curvature</span>
            <span className={`text-[10px] font-mono ${accentClass}`}>{state.bulkCurvature.toFixed(2)}</span>
          </div>
          <input 
            type="range" min="0" max="2" step="0.1" 
            value={state.bulkCurvature}
            onChange={e => setState(prev => ({ ...prev, bulkCurvature: parseFloat(e.target.value) }))}
            className="w-full h-1 bg-slate-800 rounded-full appearance-none cursor-pointer accent-emerald-500"
          />
        </section>

        <div className="p-3 rounded-lg bg-emerald-500/5 border border-emerald-500/10 space-y-2">
          <div className="flex items-center gap-2">
            <Info size={12} className={accentClass} />
            <span className="text-[9px] font-bold text-slate-400 uppercase">Theory of Spacetime</span>
          </div>
          <p className="text-[9px] text-slate-500 leading-relaxed italic">
            Spacetime is not a fundamental entity but an emergent structure generated by the multi-scale entanglement of the E8 boundary roots. Each level of the tree represents a renormalization group flow step, distilling the information of the bulk interior.
          </p>
        </div>
      </div>
    </div>
  );
};

export default MeraSlate;
